"use client";

import localFont from "next/font/local";
import Sidenav from "@/components/Sidenav";
import "./globals.css";
import { useState } from "react";
import { GiHamburgerMenu } from "react-icons/gi";
import { IconButton } from "@mui/material";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [isCollapsed, setIsCollapsed] = useState(false);

  const toggleCollapse = () => {
    setIsCollapsed(!isCollapsed);
  };


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fullContainer" style={{minHeight: '100vh', display: 'flex'}}>
          <div className={`leftContainer ${isCollapsed ? "collapsed" : ""}`} style={{backgroundColor: '#92a2a9', padding: '2rem 0'}}>
            <IconButton className="hamburgerButton" onClick={toggleCollapse} size="small" style={{color: 'white', backgroundColor: '#264653', margin: '8px'}}>
              <GiHamburgerMenu />
            </IconButton>
            <Sidenav />
          </div>
          <div className="rightContainer" style={{flexGrow: '1', height: '100%'}}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
