name: Musibara API Server CD

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Kill Existing Server Instance
        run: echo "hello"
