name: Musibara API/Client CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull API Server Image
        run: sudo docker pull wytata/musibara-api:latest
      - name: Run API Server Container
        run: sudo docker run -d -p 8000:8000 --name musibara-api-container wytata/musibara-api
