name: Musibara API/Client Dev CI

on:
  push:
    branches: ["dev"]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Log in to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build API Container
      working-directory: musibara-api
      run: docker build -t wytata/musibara-api-dev .
    - name: Push to Dockerhub
      run: docker push wytata/musibara-api-dev:latest
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Log in to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build .env File
      working-directory: musibara-client 
      run: |
        touch .env 
        echo "SPOTIFY_SECRET=${{secrets.SPOTIFY_SECRET}}" > .env
    - name: Build Client Container
      env:
        NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL_DEV}}
        NEXT_PUBLIC_SPOTIFY_ID: ${{secrets.NEXT_PUBLIC_SPOTIFY_ID}}
        NEXT_PUBLIC_SPOTIFY_REDIRECT_URI: ${{secrets.NEXT_PUBLIC_SPOTIFY_REDIRECT_URI_DEV}}
      working-directory: musibara-client
      run: docker build --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL --build-arg NEXT_PUBLIC_SPOTIFY_ID=$NEXT_PUBLIC_SPOTIFY_ID --build-arg NEXT_PUBLIC_SPOTIFY_REDIRECT_URI=$NEXT_PUBLIC_SPOTIFY_REDIRECT_URI -t wytata/musibara-client-dev .
    - name: Push to Dockerhub
      run: docker push wytata/musibara-client-dev:latest
  call-cd-workflow:
    needs: [build-api, build-client]
    uses: ./.github/workflows/cd.yml
    secrets: inherit

